### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.ScalingSettingsDto
  commentId: T:IGCLWrapper.ScalingSettingsDto
  id: ScalingSettingsDto
  parent: IGCLWrapper
  children:
  - IGCLWrapper.ScalingSettingsDto.CustomScalingX
  - IGCLWrapper.ScalingSettingsDto.CustomScalingY
  - IGCLWrapper.ScalingSettingsDto.Enable
  - IGCLWrapper.ScalingSettingsDto.FromNative(IGCLWrapper.ctl_scaling_settings_t)
  - IGCLWrapper.ScalingSettingsDto.HardwareModeSet
  - IGCLWrapper.ScalingSettingsDto.PreferredScalingType
  - IGCLWrapper.ScalingSettingsDto.ScalingType
  - IGCLWrapper.ScalingSettingsDto.Size
  - IGCLWrapper.ScalingSettingsDto.ToNative
  - IGCLWrapper.ScalingSettingsDto.Version
  langs:
  - csharp
  - vb
  name: ScalingSettingsDto
  nameWithType: ScalingSettingsDto
  fullName: IGCLWrapper.ScalingSettingsDto
  type: Struct
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ScalingSettingsDto
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2036
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: DTO for scaling settings.
  example: []
  syntax:
    content: public struct ScalingSettingsDto
    content.vb: Public Structure ScalingSettingsDto
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: IGCLWrapper.ScalingSettingsDto.Size
  commentId: F:IGCLWrapper.ScalingSettingsDto.Size
  id: Size
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: Size
  nameWithType: ScalingSettingsDto.Size
  fullName: IGCLWrapper.ScalingSettingsDto.Size
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Size
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2041
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Size of the native struct.
  example: []
  syntax:
    content: public uint Size
    return:
      type: System.UInt32
    content.vb: Public Size As UInteger
- uid: IGCLWrapper.ScalingSettingsDto.Version
  commentId: F:IGCLWrapper.ScalingSettingsDto.Version
  id: Version
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: ScalingSettingsDto.Version
  fullName: IGCLWrapper.ScalingSettingsDto.Version
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Version
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2045
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Version of the native struct.
  example: []
  syntax:
    content: public byte Version
    return:
      type: System.Byte
    content.vb: Public Version As Byte
- uid: IGCLWrapper.ScalingSettingsDto.Enable
  commentId: F:IGCLWrapper.ScalingSettingsDto.Enable
  id: Enable
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: Enable
  nameWithType: ScalingSettingsDto.Enable
  fullName: IGCLWrapper.ScalingSettingsDto.Enable
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Enable
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2049
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Enable flag.
  example: []
  syntax:
    content: public bool Enable
    return:
      type: System.Boolean
    content.vb: Public Enable As Boolean
- uid: IGCLWrapper.ScalingSettingsDto.ScalingType
  commentId: F:IGCLWrapper.ScalingSettingsDto.ScalingType
  id: ScalingType
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: ScalingType
  nameWithType: ScalingSettingsDto.ScalingType
  fullName: IGCLWrapper.ScalingSettingsDto.ScalingType
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ScalingType
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2053
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Scaling type.
  example: []
  syntax:
    content: public uint ScalingType
    return:
      type: System.UInt32
    content.vb: Public ScalingType As UInteger
- uid: IGCLWrapper.ScalingSettingsDto.CustomScalingX
  commentId: F:IGCLWrapper.ScalingSettingsDto.CustomScalingX
  id: CustomScalingX
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: CustomScalingX
  nameWithType: ScalingSettingsDto.CustomScalingX
  fullName: IGCLWrapper.ScalingSettingsDto.CustomScalingX
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CustomScalingX
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2057
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Custom scaling X value.
  example: []
  syntax:
    content: public uint CustomScalingX
    return:
      type: System.UInt32
    content.vb: Public CustomScalingX As UInteger
- uid: IGCLWrapper.ScalingSettingsDto.CustomScalingY
  commentId: F:IGCLWrapper.ScalingSettingsDto.CustomScalingY
  id: CustomScalingY
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: CustomScalingY
  nameWithType: ScalingSettingsDto.CustomScalingY
  fullName: IGCLWrapper.ScalingSettingsDto.CustomScalingY
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: CustomScalingY
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2061
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Custom scaling Y value.
  example: []
  syntax:
    content: public uint CustomScalingY
    return:
      type: System.UInt32
    content.vb: Public CustomScalingY As UInteger
- uid: IGCLWrapper.ScalingSettingsDto.HardwareModeSet
  commentId: F:IGCLWrapper.ScalingSettingsDto.HardwareModeSet
  id: HardwareModeSet
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: HardwareModeSet
  nameWithType: ScalingSettingsDto.HardwareModeSet
  fullName: IGCLWrapper.ScalingSettingsDto.HardwareModeSet
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: HardwareModeSet
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2065
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Hardware mode set flag.
  example: []
  syntax:
    content: public bool HardwareModeSet
    return:
      type: System.Boolean
    content.vb: Public HardwareModeSet As Boolean
- uid: IGCLWrapper.ScalingSettingsDto.PreferredScalingType
  commentId: F:IGCLWrapper.ScalingSettingsDto.PreferredScalingType
  id: PreferredScalingType
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: PreferredScalingType
  nameWithType: ScalingSettingsDto.PreferredScalingType
  fullName: IGCLWrapper.ScalingSettingsDto.PreferredScalingType
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: PreferredScalingType
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2069
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Preferred scaling type.
  example: []
  syntax:
    content: public uint PreferredScalingType
    return:
      type: System.UInt32
    content.vb: Public PreferredScalingType As UInteger
- uid: IGCLWrapper.ScalingSettingsDto.FromNative(IGCLWrapper.ctl_scaling_settings_t)
  commentId: M:IGCLWrapper.ScalingSettingsDto.FromNative(IGCLWrapper.ctl_scaling_settings_t)
  id: FromNative(IGCLWrapper.ctl_scaling_settings_t)
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: FromNative(ctl_scaling_settings_t)
  nameWithType: ScalingSettingsDto.FromNative(ctl_scaling_settings_t)
  fullName: IGCLWrapper.ScalingSettingsDto.FromNative(IGCLWrapper.ctl_scaling_settings_t)
  type: Method
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: FromNative
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2076
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Create a DTO from a native struct.
  example: []
  syntax:
    content: public static ScalingSettingsDto FromNative(ctl_scaling_settings_t native)
    parameters:
    - id: native
      type: IGCLWrapper.ctl_scaling_settings_t
      description: Native struct.
    return:
      type: IGCLWrapper.ScalingSettingsDto
      description: Scaling settings DTO.
    content.vb: Public Shared Function FromNative(native As ctl_scaling_settings_t) As ScalingSettingsDto
  overload: IGCLWrapper.ScalingSettingsDto.FromNative*
- uid: IGCLWrapper.ScalingSettingsDto.ToNative
  commentId: M:IGCLWrapper.ScalingSettingsDto.ToNative
  id: ToNative
  parent: IGCLWrapper.ScalingSettingsDto
  langs:
  - csharp
  - vb
  name: ToNative()
  nameWithType: ScalingSettingsDto.ToNative()
  fullName: IGCLWrapper.ScalingSettingsDto.ToNative()
  type: Method
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ToNative
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 2095
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Convert this DTO to a native struct.
  example: []
  syntax:
    content: public ctl_scaling_settings_t ToNative()
    return:
      type: IGCLWrapper.ctl_scaling_settings_t
      description: Scaling settings struct.
    content.vb: Public Function ToNative() As ctl_scaling_settings_t
  overload: IGCLWrapper.ScalingSettingsDto.ToNative*
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: IGCLWrapper.ScalingSettingsDto.FromNative*
  commentId: Overload:IGCLWrapper.ScalingSettingsDto.FromNative
  href: IGCLWrapper.ScalingSettingsDto.html#IGCLWrapper_ScalingSettingsDto_FromNative_IGCLWrapper_ctl_scaling_settings_t_
  name: FromNative
  nameWithType: ScalingSettingsDto.FromNative
  fullName: IGCLWrapper.ScalingSettingsDto.FromNative
- uid: IGCLWrapper.ctl_scaling_settings_t
  commentId: T:IGCLWrapper.ctl_scaling_settings_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_scaling_settings_t.html
  name: ctl_scaling_settings_t
  nameWithType: ctl_scaling_settings_t
  fullName: IGCLWrapper.ctl_scaling_settings_t
- uid: IGCLWrapper.ScalingSettingsDto
  commentId: T:IGCLWrapper.ScalingSettingsDto
  parent: IGCLWrapper
  href: IGCLWrapper.ScalingSettingsDto.html
  name: ScalingSettingsDto
  nameWithType: ScalingSettingsDto
  fullName: IGCLWrapper.ScalingSettingsDto
- uid: IGCLWrapper.ScalingSettingsDto.ToNative*
  commentId: Overload:IGCLWrapper.ScalingSettingsDto.ToNative
  href: IGCLWrapper.ScalingSettingsDto.html#IGCLWrapper_ScalingSettingsDto_ToNative
  name: ToNative
  nameWithType: ScalingSettingsDto.ToNative
  fullName: IGCLWrapper.ScalingSettingsDto.ToNative
