### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.WireFormatConfigDto
  commentId: T:IGCLWrapper.WireFormatConfigDto
  id: WireFormatConfigDto
  parent: IGCLWrapper
  children:
  - IGCLWrapper.WireFormatConfigDto.FromNative(IGCLWrapper.ctl_get_set_wire_format_config_t)
  - IGCLWrapper.WireFormatConfigDto.Operation
  - IGCLWrapper.WireFormatConfigDto.Size
  - IGCLWrapper.WireFormatConfigDto.SupportedWireFormat
  - IGCLWrapper.WireFormatConfigDto.ToNative
  - IGCLWrapper.WireFormatConfigDto.Version
  - IGCLWrapper.WireFormatConfigDto.WireFormat
  langs:
  - csharp
  - vb
  name: WireFormatConfigDto
  nameWithType: WireFormatConfigDto
  fullName: IGCLWrapper.WireFormatConfigDto
  type: Struct
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: WireFormatConfigDto
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1447
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: DTO for wire format settings.
  example: []
  syntax:
    content: public struct WireFormatConfigDto
    content.vb: Public Structure WireFormatConfigDto
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: IGCLWrapper.WireFormatConfigDto.Size
  commentId: F:IGCLWrapper.WireFormatConfigDto.Size
  id: Size
  parent: IGCLWrapper.WireFormatConfigDto
  langs:
  - csharp
  - vb
  name: Size
  nameWithType: WireFormatConfigDto.Size
  fullName: IGCLWrapper.WireFormatConfigDto.Size
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Size
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1453
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Size of the native struct.
  example: []
  syntax:
    content: public uint Size
    return:
      type: System.UInt32
    content.vb: Public Size As UInteger
- uid: IGCLWrapper.WireFormatConfigDto.Version
  commentId: F:IGCLWrapper.WireFormatConfigDto.Version
  id: Version
  parent: IGCLWrapper.WireFormatConfigDto
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: WireFormatConfigDto.Version
  fullName: IGCLWrapper.WireFormatConfigDto.Version
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Version
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1457
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Version of the native struct.
  example: []
  syntax:
    content: public byte Version
    return:
      type: System.Byte
    content.vb: Public Version As Byte
- uid: IGCLWrapper.WireFormatConfigDto.Operation
  commentId: F:IGCLWrapper.WireFormatConfigDto.Operation
  id: Operation
  parent: IGCLWrapper.WireFormatConfigDto
  langs:
  - csharp
  - vb
  name: Operation
  nameWithType: WireFormatConfigDto.Operation
  fullName: IGCLWrapper.WireFormatConfigDto.Operation
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Operation
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1461
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Wire format operation type.
  example: []
  syntax:
    content: public ctl_wire_format_operation_type_t Operation
    return:
      type: IGCLWrapper.ctl_wire_format_operation_type_t
    content.vb: Public Operation As ctl_wire_format_operation_type_t
- uid: IGCLWrapper.WireFormatConfigDto.SupportedWireFormat
  commentId: F:IGCLWrapper.WireFormatConfigDto.SupportedWireFormat
  id: SupportedWireFormat
  parent: IGCLWrapper.WireFormatConfigDto
  langs:
  - csharp
  - vb
  name: SupportedWireFormat
  nameWithType: WireFormatConfigDto.SupportedWireFormat
  fullName: IGCLWrapper.WireFormatConfigDto.SupportedWireFormat
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: SupportedWireFormat
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1465
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Supported wire format values.
  example: []
  syntax:
    content: public ctl_wire_format_t[]? SupportedWireFormat
    return:
      type: IGCLWrapper.ctl_wire_format_t[]
    content.vb: Public SupportedWireFormat As ctl_wire_format_t()
- uid: IGCLWrapper.WireFormatConfigDto.WireFormat
  commentId: F:IGCLWrapper.WireFormatConfigDto.WireFormat
  id: WireFormat
  parent: IGCLWrapper.WireFormatConfigDto
  langs:
  - csharp
  - vb
  name: WireFormat
  nameWithType: WireFormatConfigDto.WireFormat
  fullName: IGCLWrapper.WireFormatConfigDto.WireFormat
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: WireFormat
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1469
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Selected wire format.
  example: []
  syntax:
    content: public ctl_wire_format_t WireFormat
    return:
      type: IGCLWrapper.ctl_wire_format_t
    content.vb: Public WireFormat As ctl_wire_format_t
- uid: IGCLWrapper.WireFormatConfigDto.FromNative(IGCLWrapper.ctl_get_set_wire_format_config_t)
  commentId: M:IGCLWrapper.WireFormatConfigDto.FromNative(IGCLWrapper.ctl_get_set_wire_format_config_t)
  id: FromNative(IGCLWrapper.ctl_get_set_wire_format_config_t)
  parent: IGCLWrapper.WireFormatConfigDto
  langs:
  - csharp
  - vb
  name: FromNative(ctl_get_set_wire_format_config_t)
  nameWithType: WireFormatConfigDto.FromNative(ctl_get_set_wire_format_config_t)
  fullName: IGCLWrapper.WireFormatConfigDto.FromNative(IGCLWrapper.ctl_get_set_wire_format_config_t)
  type: Method
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: FromNative
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1476
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Create a DTO from a native struct.
  example: []
  syntax:
    content: public static WireFormatConfigDto FromNative(ctl_get_set_wire_format_config_t native)
    parameters:
    - id: native
      type: IGCLWrapper.ctl_get_set_wire_format_config_t
      description: Native struct.
    return:
      type: IGCLWrapper.WireFormatConfigDto
      description: Wire format settings DTO.
    content.vb: Public Shared Function FromNative(native As ctl_get_set_wire_format_config_t) As WireFormatConfigDto
  overload: IGCLWrapper.WireFormatConfigDto.FromNative*
- uid: IGCLWrapper.WireFormatConfigDto.ToNative
  commentId: M:IGCLWrapper.WireFormatConfigDto.ToNative
  id: ToNative
  parent: IGCLWrapper.WireFormatConfigDto
  langs:
  - csharp
  - vb
  name: ToNative()
  nameWithType: WireFormatConfigDto.ToNative()
  fullName: IGCLWrapper.WireFormatConfigDto.ToNative()
  type: Method
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: develop
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ToNative
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1492
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  summary: Convert this DTO to a native struct.
  example: []
  syntax:
    content: public ctl_get_set_wire_format_config_t ToNative()
    return:
      type: IGCLWrapper.ctl_get_set_wire_format_config_t
      description: Wire format settings struct.
    content.vb: Public Function ToNative() As ctl_get_set_wire_format_config_t
  overload: IGCLWrapper.WireFormatConfigDto.ToNative*
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: IGCLWrapper.ctl_wire_format_operation_type_t
  commentId: T:IGCLWrapper.ctl_wire_format_operation_type_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_wire_format_operation_type_t.html
  name: ctl_wire_format_operation_type_t
  nameWithType: ctl_wire_format_operation_type_t
  fullName: IGCLWrapper.ctl_wire_format_operation_type_t
- uid: IGCLWrapper.ctl_wire_format_t[]
  isExternal: true
  href: IGCLWrapper.ctl_wire_format_t.html
  name: ctl_wire_format_t[]
  nameWithType: ctl_wire_format_t[]
  fullName: IGCLWrapper.ctl_wire_format_t[]
  nameWithType.vb: ctl_wire_format_t()
  fullName.vb: IGCLWrapper.ctl_wire_format_t()
  name.vb: ctl_wire_format_t()
  spec.csharp:
  - uid: IGCLWrapper.ctl_wire_format_t
    name: ctl_wire_format_t
    href: IGCLWrapper.ctl_wire_format_t.html
  - name: '['
  - name: ']'
  spec.vb:
  - uid: IGCLWrapper.ctl_wire_format_t
    name: ctl_wire_format_t
    href: IGCLWrapper.ctl_wire_format_t.html
  - name: (
  - name: )
- uid: IGCLWrapper.ctl_wire_format_t
  commentId: T:IGCLWrapper.ctl_wire_format_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_wire_format_t.html
  name: ctl_wire_format_t
  nameWithType: ctl_wire_format_t
  fullName: IGCLWrapper.ctl_wire_format_t
- uid: IGCLWrapper.WireFormatConfigDto.FromNative*
  commentId: Overload:IGCLWrapper.WireFormatConfigDto.FromNative
  href: IGCLWrapper.WireFormatConfigDto.html#IGCLWrapper_WireFormatConfigDto_FromNative_IGCLWrapper_ctl_get_set_wire_format_config_t_
  name: FromNative
  nameWithType: WireFormatConfigDto.FromNative
  fullName: IGCLWrapper.WireFormatConfigDto.FromNative
- uid: IGCLWrapper.ctl_get_set_wire_format_config_t
  commentId: T:IGCLWrapper.ctl_get_set_wire_format_config_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_get_set_wire_format_config_t.html
  name: ctl_get_set_wire_format_config_t
  nameWithType: ctl_get_set_wire_format_config_t
  fullName: IGCLWrapper.ctl_get_set_wire_format_config_t
- uid: IGCLWrapper.WireFormatConfigDto
  commentId: T:IGCLWrapper.WireFormatConfigDto
  parent: IGCLWrapper
  href: IGCLWrapper.WireFormatConfigDto.html
  name: WireFormatConfigDto
  nameWithType: WireFormatConfigDto
  fullName: IGCLWrapper.WireFormatConfigDto
- uid: IGCLWrapper.WireFormatConfigDto.ToNative*
  commentId: Overload:IGCLWrapper.WireFormatConfigDto.ToNative
  href: IGCLWrapper.WireFormatConfigDto.html#IGCLWrapper_WireFormatConfigDto_ToNative
  name: ToNative
  nameWithType: WireFormatConfigDto.ToNative
  fullName: IGCLWrapper.WireFormatConfigDto.ToNative
