### YamlMime:ManagedReference
items:
- uid: IGCLWrapper.LaceConfigDto
  commentId: T:IGCLWrapper.LaceConfigDto
  id: LaceConfigDto
  parent: IGCLWrapper
  children:
  - IGCLWrapper.LaceConfigDto.Enabled
  - IGCLWrapper.LaceConfigDto.FromNative(IGCLWrapper.ctl_lace_config_t)
  - IGCLWrapper.LaceConfigDto.LaceConfig
  - IGCLWrapper.LaceConfigDto.OpTypeGet
  - IGCLWrapper.LaceConfigDto.OpTypeSet
  - IGCLWrapper.LaceConfigDto.Size
  - IGCLWrapper.LaceConfigDto.ToNative
  - IGCLWrapper.LaceConfigDto.Trigger
  - IGCLWrapper.LaceConfigDto.Version
  langs:
  - csharp
  - vb
  name: LaceConfigDto
  nameWithType: LaceConfigDto
  fullName: IGCLWrapper.LaceConfigDto
  type: Struct
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: LaceConfigDto
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1146
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public struct LaceConfigDto
    content.vb: Public Structure LaceConfigDto
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: IGCLWrapper.LaceConfigDto.Size
  commentId: F:IGCLWrapper.LaceConfigDto.Size
  id: Size
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: Size
  nameWithType: LaceConfigDto.Size
  fullName: IGCLWrapper.LaceConfigDto.Size
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Size
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1148
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public uint Size
    return:
      type: System.UInt32
    content.vb: Public Size As UInteger
- uid: IGCLWrapper.LaceConfigDto.Version
  commentId: F:IGCLWrapper.LaceConfigDto.Version
  id: Version
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: LaceConfigDto.Version
  fullName: IGCLWrapper.LaceConfigDto.Version
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Version
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1149
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public byte Version
    return:
      type: System.Byte
    content.vb: Public Version As Byte
- uid: IGCLWrapper.LaceConfigDto.Enabled
  commentId: F:IGCLWrapper.LaceConfigDto.Enabled
  id: Enabled
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: LaceConfigDto.Enabled
  fullName: IGCLWrapper.LaceConfigDto.Enabled
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Enabled
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1150
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public bool Enabled
    return:
      type: System.Boolean
    content.vb: Public Enabled As Boolean
- uid: IGCLWrapper.LaceConfigDto.OpTypeGet
  commentId: F:IGCLWrapper.LaceConfigDto.OpTypeGet
  id: OpTypeGet
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: OpTypeGet
  nameWithType: LaceConfigDto.OpTypeGet
  fullName: IGCLWrapper.LaceConfigDto.OpTypeGet
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: OpTypeGet
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1151
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public uint OpTypeGet
    return:
      type: System.UInt32
    content.vb: Public OpTypeGet As UInteger
- uid: IGCLWrapper.LaceConfigDto.OpTypeSet
  commentId: F:IGCLWrapper.LaceConfigDto.OpTypeSet
  id: OpTypeSet
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: OpTypeSet
  nameWithType: LaceConfigDto.OpTypeSet
  fullName: IGCLWrapper.LaceConfigDto.OpTypeSet
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: OpTypeSet
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1152
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public ctl_set_operation_t OpTypeSet
    return:
      type: IGCLWrapper.ctl_set_operation_t
    content.vb: Public OpTypeSet As ctl_set_operation_t
- uid: IGCLWrapper.LaceConfigDto.Trigger
  commentId: F:IGCLWrapper.LaceConfigDto.Trigger
  id: Trigger
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: Trigger
  nameWithType: LaceConfigDto.Trigger
  fullName: IGCLWrapper.LaceConfigDto.Trigger
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: Trigger
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1153
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public uint Trigger
    return:
      type: System.UInt32
    content.vb: Public Trigger As UInteger
- uid: IGCLWrapper.LaceConfigDto.LaceConfig
  commentId: F:IGCLWrapper.LaceConfigDto.LaceConfig
  id: LaceConfig
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: LaceConfig
  nameWithType: LaceConfigDto.LaceConfig
  fullName: IGCLWrapper.LaceConfigDto.LaceConfig
  type: Field
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: LaceConfig
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1154
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public ctl_lace_aggr_config_t LaceConfig
    return:
      type: IGCLWrapper.ctl_lace_aggr_config_t
    content.vb: Public LaceConfig As ctl_lace_aggr_config_t
- uid: IGCLWrapper.LaceConfigDto.FromNative(IGCLWrapper.ctl_lace_config_t)
  commentId: M:IGCLWrapper.LaceConfigDto.FromNative(IGCLWrapper.ctl_lace_config_t)
  id: FromNative(IGCLWrapper.ctl_lace_config_t)
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: FromNative(ctl_lace_config_t)
  nameWithType: LaceConfigDto.FromNative(ctl_lace_config_t)
  fullName: IGCLWrapper.LaceConfigDto.FromNative(IGCLWrapper.ctl_lace_config_t)
  type: Method
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: FromNative
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1156
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public static LaceConfigDto FromNative(ctl_lace_config_t native)
    parameters:
    - id: native
      type: IGCLWrapper.ctl_lace_config_t
    return:
      type: IGCLWrapper.LaceConfigDto
    content.vb: Public Shared Function FromNative(native As ctl_lace_config_t) As LaceConfigDto
  overload: IGCLWrapper.LaceConfigDto.FromNative*
- uid: IGCLWrapper.LaceConfigDto.ToNative
  commentId: M:IGCLWrapper.LaceConfigDto.ToNative
  id: ToNative
  parent: IGCLWrapper.LaceConfigDto
  langs:
  - csharp
  - vb
  name: ToNative()
  nameWithType: LaceConfigDto.ToNative()
  fullName: IGCLWrapper.LaceConfigDto.ToNative()
  type: Method
  source:
    remote:
      path: IGCLWrapper/IGCLDisplayHelper.cs
      branch: feature-facade-v1
      repo: https://github.com/terrymacdonald/IGCLWrapper.git
    id: ToNative
    path: ../IGCLWrapper/IGCLDisplayHelper.cs
    startLine: 1170
  assemblies:
  - IGCLWrapper
  namespace: IGCLWrapper
  syntax:
    content: public ctl_lace_config_t ToNative()
    return:
      type: IGCLWrapper.ctl_lace_config_t
    content.vb: Public Function ToNative() As ctl_lace_config_t
  overload: IGCLWrapper.LaceConfigDto.ToNative*
references:
- uid: IGCLWrapper
  commentId: N:IGCLWrapper
  href: IGCLWrapper.html
  name: IGCLWrapper
  nameWithType: IGCLWrapper
  fullName: IGCLWrapper
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: IGCLWrapper.ctl_set_operation_t
  commentId: T:IGCLWrapper.ctl_set_operation_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_set_operation_t.html
  name: ctl_set_operation_t
  nameWithType: ctl_set_operation_t
  fullName: IGCLWrapper.ctl_set_operation_t
- uid: IGCLWrapper.ctl_lace_aggr_config_t
  commentId: T:IGCLWrapper.ctl_lace_aggr_config_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_lace_aggr_config_t.html
  name: ctl_lace_aggr_config_t
  nameWithType: ctl_lace_aggr_config_t
  fullName: IGCLWrapper.ctl_lace_aggr_config_t
- uid: IGCLWrapper.LaceConfigDto.FromNative*
  commentId: Overload:IGCLWrapper.LaceConfigDto.FromNative
  href: IGCLWrapper.LaceConfigDto.html#IGCLWrapper_LaceConfigDto_FromNative_IGCLWrapper_ctl_lace_config_t_
  name: FromNative
  nameWithType: LaceConfigDto.FromNative
  fullName: IGCLWrapper.LaceConfigDto.FromNative
- uid: IGCLWrapper.ctl_lace_config_t
  commentId: T:IGCLWrapper.ctl_lace_config_t
  parent: IGCLWrapper
  href: IGCLWrapper.ctl_lace_config_t.html
  name: ctl_lace_config_t
  nameWithType: ctl_lace_config_t
  fullName: IGCLWrapper.ctl_lace_config_t
- uid: IGCLWrapper.LaceConfigDto
  commentId: T:IGCLWrapper.LaceConfigDto
  parent: IGCLWrapper
  href: IGCLWrapper.LaceConfigDto.html
  name: LaceConfigDto
  nameWithType: LaceConfigDto
  fullName: IGCLWrapper.LaceConfigDto
- uid: IGCLWrapper.LaceConfigDto.ToNative*
  commentId: Overload:IGCLWrapper.LaceConfigDto.ToNative
  href: IGCLWrapper.LaceConfigDto.html#IGCLWrapper_LaceConfigDto_ToNative
  name: ToNative
  nameWithType: LaceConfigDto.ToNative
  fullName: IGCLWrapper.LaceConfigDto.ToNative
